import React, { useState, useEffect } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Home } from 'lucide-react';
import { cn } from '@/lib/utils';
import { getReportById } from '@/lib/api/reports';
import { useLanguage } from '@/contexts/LanguageContext';
import {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb';

interface BreadcrumbItemData {
  label: string;
  href?: string;
  current?: boolean;
}

interface BreadcrumbsProps {
  items?: BreadcrumbItemData[];
  className?: string;
}

const Breadcrumbs: React.FC<BreadcrumbsProps> = ({ items, className }) => {
  const { t } = useLanguage();
  const location = useLocation();
  const [reportTitle, setReportTitle] = useState<string | null>(null);

  // Fetch report title when on a report page
  useEffect(() => {
    const pathSegments = location.pathname.split('/').filter(Boolean);
    if (pathSegments.includes('reports')) {
      const reportIndex = pathSegments.indexOf('reports');
      const reportId = pathSegments[reportIndex + 1];
      
      if (reportId && reportId !== 'create') {
        // Fetch report data
        getReportById(reportId)
          .then(report => {
            setReportTitle(report.title);
          })
          .catch(error => {
            console.error('Failed to fetch report for breadcrumb:', error);
            setReportTitle(null);
          });
      } else {
        setReportTitle(null);
      }
    } else {
      setReportTitle(null);
    }
  }, [location.pathname]);

  // Auto-generate breadcrumbs if not provided
  const autoGeneratedItems: BreadcrumbItemData[] = React.useMemo(() => {
    if (items) return items;

    const pathSegments = location.pathname.split('/').filter(Boolean);
    const breadcrumbs: BreadcrumbItemData[] = [];

    // Handle common patterns
    if (pathSegments.includes('reports')) {
      const reportIndex = pathSegments.indexOf('reports');
      const reportId = pathSegments[reportIndex + 1];
      
      if (reportId) {
        breadcrumbs.push({
          label: t('nav.reports'),
          href: '/dashboard'
        });
        
        // Add report-specific breadcrumb
        const action = pathSegments[reportIndex + 2];
        
        if (reportId === 'create') {
          breadcrumbs.push({ label: t('nav.newReport'), current: true });
        } else {
          const reportLabel = reportTitle || t('common.loading');
          
          if (action === 'preview') {
            breadcrumbs.push({ label: `${reportLabel} - ${t('nav.preview')}`, current: true });
          } else if (action === 'preview2') {
            breadcrumbs.push({ label: `${reportLabel} - ${t('nav.editor')}`, current: true });
          } else if (action === 'edit-full') {
            breadcrumbs.push({ label: `${reportLabel} - Full Edit`, current: true });
          } else if (action === 'unified-preview') {
            breadcrumbs.push({ label: reportLabel, current: true });
          } else {
            breadcrumbs.push({ label: reportLabel, current: true });
          }
        }
      }
    } else if (pathSegments.includes('admin')) {
      const adminIndex = pathSegments.indexOf('admin');
      const adminSection = pathSegments[adminIndex + 1];
      
      if (adminSection === 'departments') {
        breadcrumbs.push({ label: t('nav.administration') });
        breadcrumbs.push({ label: t('nav.manageDepartments'), current: true });
      } else if (adminSection === 'report-templates') {
        breadcrumbs.push({ label: t('nav.administration') });
        breadcrumbs.push({ label: 'Report Templates', current: true });
      } else if (adminSection === 'users') {
        breadcrumbs.push({ label: t('nav.administration') });
        breadcrumbs.push({ label: 'Manage Users', current: true });
      } else {
        breadcrumbs.push({ label: t('nav.administration'), current: true });
      }
    }

    return breadcrumbs;
  }, [items, location.pathname, reportTitle]);

  const isOnDashboard = location.pathname === '/dashboard';

  return (
    <Breadcrumb className={className}>
      <BreadcrumbList>
        {/* Home icon - show as current page if on dashboard, otherwise as link */}
        <BreadcrumbItem>
          {isOnDashboard ? (
            <BreadcrumbPage className="flex items-center gap-2 px-2 py-1 rounded-md bg-background/50 font-medium">
              <Home className="h-4 w-4" />
              <span>{t('app.dashboard')}</span>
            </BreadcrumbPage>
          ) : (
            <BreadcrumbLink asChild>
              <Link 
                to="/dashboard" 
                aria-label="Dashboard"
                className="flex items-center gap-2 px-2 py-1 rounded-md hover:bg-background/80 transition-colors"
              >
                <Home className="h-4 w-4" />
                <span>{t('app.dashboard')}</span>
              </Link>
            </BreadcrumbLink>
          )}
        </BreadcrumbItem>
        
        {autoGeneratedItems.length > 0 && (
          <>
            <BreadcrumbSeparator />
            {autoGeneratedItems.map((item, index) => (
              <React.Fragment key={index}>
                {index > 0 && <BreadcrumbSeparator />}
                <BreadcrumbItem>
                  {item.current ? (
                    <BreadcrumbPage className="font-medium">
                      {item.label}
                    </BreadcrumbPage>
                  ) : (
                    <BreadcrumbLink asChild>
                      <Link to={item.href || '#'}>
                        {item.label}
                      </Link>
                    </BreadcrumbLink>
                  )}
                </BreadcrumbItem>
              </React.Fragment>
            ))}
          </>
        )}
      </BreadcrumbList>
    </Breadcrumb>
  );
};

export default Breadcrumbs;