// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfalhxsuzydnusotcrme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYWxoeHN1enlkbnVzb3Rjcm1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjk2NTQsImV4cCI6MjA2MjgwNTY1NH0.R-zb5l93ujWQfTxIXVaIB1VLlYFdRQwXDi3b9TXYIQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);